apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jwa61g3j1-python
  janus-idp.io/tekton: jwa61g3j1-python
  backstage.io/kubernetes-id: jwa61g3j1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jwa61g3j1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
